apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinelguard.fullname" . }}-env
type: Opaque
stringData:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentinelguard.fullname" . }}-config
data:
  gateway.yaml: |
{{ .Values.gatewayConfig | indent 4 }}
