apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinelguard-gateway
  namespace: sentinelguard
  labels:
    app.kubernetes.io/name: sentinelguard-gateway
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: sentinelguard.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentinelguard-gateway
                port:
                  number: 8080
