apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinelguard-gateway-data
  namespace: sentinelguard
  labels:
    app.kubernetes.io/name: sentinelguard-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
